version: '3'

services:
  test:
    image: ghnuberath/testing-marshal

  marshal:
    image: ghnuberath/marshal
    environment:
      STACK_NAME: 'marshal-test'
      REFRESH_INTERVAL: 30000
    depends_on:
      - redis
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        window: 15s

