version: '3'

services:
  test:
    image: smcintyre/testing-marshal

  marshal:
    image: smcintyre/marshal:1.2.0
    environment:
      STACK_NAME: 'marshal-test'
      REFRESH_INTERVAL: 30000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        window: 15s

